spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/aulamicroservices?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: 123
server:
  port: 8080
  servlet:
    context-path: /gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/

zuul:
  sensitive-headers: Cookie

jwt:
  config:
    login-url: /auth/login

